### ISSUE TITLE
Can't convert Zelda

### ISSUE THREAD

**Issue by chronoss09** [The-4n/4NXCI#10]
I can't convert Zelda (rev001) on nsp, it give me a small file with 330mo with Alpha 4 and error with Alpha 5

**Comment by kot2002** [comment]
Currently known games which don't convert properly:
Donkey Kong Country: Tropical Freeze (rev001)
Super Mario Odyssey (rev001)
Mario Kart 8 Deluxe (rev002)
The Legend of Zelda: Breath of the Wild (rev001)
The Legend of Zelda: Breath of the Wild (rev002)
Sonic Mania Plus

**Comment by zhaoyupingcn** [comment]
alpha 5 cannot convert any xci file.   drop a xci file to 4nxci.exe then a window pop up & disappear rapidly,  nothing happend.   64bit win7 win10-chs same.

**Comment by kot2002** [comment]
@zhaoyupingcn Try gathering all the files in the same folder. You need 4nxci.exe, keys.dat, [to be converted].XCI to do converting.

**Comment by The-4n** [comment]
this issue is solved in v0.9-beta.1

**Comment by chronoss09** [comment]
tested With Sonic Maniac Plus and it give 3 NSP : 
![ec1c3bbd57665ab61f41d99898cdc60e](https://user-images.githubusercontent.com/17669980/44302350-a48f4800-a31e-11e8-892a-f76404ae05fd.png)
