### ISSUE TITLE
Conversion took forever on Alpha5

### ISSUE THREAD

**Issue by ABeltramo** [The-4n/4NXCI#11]
Same .xci file and .dat on Alpha4 took 1 minute, on Alpha5 seems to never stopping. With little .xci (under 1GB) seems to convert fine, when the size grow up seems unable to complete the process.
The terminal is stopped on the first phase:  `Saving [...].nca to 4nxci_extracted_xci/[...].nca`.

Both version compiled from source on the same machine: OSX 10.12.6 using make.

**Comment by The-4n** [comment]
check v0.9-beta.1 and tell me the result

**Comment by The-4n** [comment]
check v0.9-beta.1 and tell me the result
