### ISSUE TITLE
NPS converted don't work conrrectly

### ISSUE THREAD

**Issue by chronoss09** [The-4n/4NXCI#13]
Sonic Mania Plus.xci, after convert, i got 3 files since beta 1: 
![44302350-a48f4800-a31e-11e8-892a-f76404ae05fd](https://user-images.githubusercontent.com/17669980/44313787-1ee6c780-a406-11e8-844c-a5582845fff3.png)
After install : 
v0 work well but with the update and the dlc, error for a account of the game :(

Same thing with Zelda, can't update the game :-1:

**Comment by The-4n** [comment]
it's not conversion issue
you don't have proper sig patches

**Comment by The-4n** [comment]
your cfw sig patches are bad ones
use updated version of your cfw or use some other cfw

**Comment by chronoss09** [comment]
I've ReiNX v1.2 and SX OS !

**Comment by The-4n** [comment]
if you get nsp file after conversion, it means the conversion process is 100% correct
and always try latest version

**Comment by chronoss09** [comment]
Tested with all syg patches available but all give me samething... i have 2 nsp and the game work with only these 2 file. can't update the game...

**Comment by chronoss09** [comment]
Ok, let me try....

**Comment by chronoss09** [comment]
After conversion, i have 2 file and those file instaled but i can't launch the. It ask a update...
After installed the last update, game freeze aigain...

In DevMenu app, there is an option to ignore the update of the game "Reset RequireVersion", with that, i can launch the 2 file installed but with the update, i have the same problem...

Sorry for my english :-1:

**Comment by chronoss09** [comment]
Someone told me others game doen't work : 
Minecraft
Sniperclips 
donkey kong (only 20mo for a nspl)
puyo puyo tetris

**Comment by The-4n** [comment]
i got feedback from some users and the games you mentioned convert properly with v1.10 and work fine
