### ISSUE TITLE
The patches are wrong

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [The-4n/4NXCI#14]
After looking at the stock (exFAT) FS.kip, and the ``nosigchk``'d (exFAT) FS.kip, the value at the offset described is ``50 B3 6B 05``, not ``9A E3 FF 97``. In fact, the value ``9A E3 FF 97`` doesn't even exist in the entire kip.

**Comment by The-4n** [comment]
first of all, there's no need to use patches anymore, you can use converted files on any cfw (with sig patches)
second, patches are right and already implemented in reinx for all firmwares
