### ISSUE TITLE
Can't convert XCI to NSP : Let's Sing 2019

### ISSUE THREAD

**Issue by MechaPoulpe** [The-4n/4NXCI#18]
Hi, every other game that I'd convert work perfectly (thanks a lot for that application !) but with the game Let' Sing 2019, the DOS box close instantly and the game is not converted (just some .nca are extracted)

I'm using the version 2.0 on windows 10

**Comment by The-4n** [comment]
I've tested it and it works without problem

Make sure that your keys are up-to-date and your xci is not corrupted
