### ISSUE TITLE
Saving/Processing in CMD Directory, not exe directory

### ISSUE THREAD

**Issue by imPRAGMA** [The-4n/4NXCI#20]
pop open a CMD, cd to %USERPROFILE% or something and run the exe from a folder on your desktop, and it will happen

**Comment by The-4n** [comment]
I'll add options for changing output and temp directory

**Comment by imPRAGMA** [comment]
Yeah just use exe's path not the commandline directory (WOrking Directory I believe)
Also when I put the NSP on SX OS, it had no information and wouldnt install :/

**Comment by riverar** [comment]
> Yeah just use exe's path not the commandline directory (WOrking Directory I believe)
> Also when I put the NSP on SX OS, it had no information and wouldnt install :/

Working in the current directory, not executable location, is standard on Windows and should be used.

**Comment by The-4n** [comment]
Options are added in 2.10
