### ISSUE TITLE
[Feature Request] Option to set the nsp filename equal the game name

### ISSUE THREAD

**Issue by shyim** [The-4n/4NXCI#21]
When i convert multiple games i have no idea which file what is 🙈

**Comment by The-4n** [comment]
I'll add it in future releases as an option

**Comment by dyerseve** [comment]
Fully customizable naming would be nice, for example, if the title ends in 800 add a tag like [UPD] and include the version number of the update. But anything is better than just the title id.

**Comment by The-4n** [comment]
Added in latest version
use -r option
