### ISSUE TITLE
not working with Super Smash Bros. Ultimate

### ISSUE THREAD

**Issue by PeterMaxu** [The-4n/4NXCI#22]

**Comment by The-4n** [comment]
Give me the full name of your dump so i can check

**Comment by PeterMaxu** [comment]
01006A800016E000 Super Smash Bros. Ultimate EUR VENOM

**Comment by The-4n** [comment]
I'll check it

**Comment by The-4n** [comment]
Can you give me more information about the problem?
4NXCI doesn't convert or the converted file doesn't works?

**Comment by mcorbett26** [comment]
It stops at making NCA and never converts to an NSP

**Comment by The-4n** [comment]
Can you give me the full 4NXCI log?
launch it with command prompt using .\4nxci.exe .\game.xci

**Comment by mcorbett26** [comment]
I am sorry, i am savvy but not that savvy, i don't understand

**Comment by mcorbett26** [comment]
![image](https://user-images.githubusercontent.com/401986/49919603-5cafa600-fe64-11e8-9289-2e476936c8a8.png)

**Comment by The-4n** [comment]
I checked it myself
Whether your downloaded file is corrupted or your keys are wrong

**Comment by mcorbett26** [comment]
Fair enough, thanks for supporting your awesome app
