### ISSUE TITLE
Auto set keys

### ISSUE THREAD

**Issue by TehPsychedelic** [The-4n/4NXCI#29]
Would you be against setting the keys field to (in order)
1. keys.dat/prod.keys location on .exe folder if found
2. prod.keys location on ~/.switch/.
3. Empty (current)

**Comment by The-4n** [comment]
I discussed it before on discord
I don't have any plan for reading keys from any file other than keys.dat unless user pass it with -k

**Comment by TehPsychedelic** [comment]
Oh sorry but I forgot to mention, this is on the UI. With that said would you be against setting keys.dat if found as text content of keys UI field?

**Comment by TehPsychedelic** [comment]
#30
