### ISSUE TITLE
GUI - Temporary Folder

### ISSUE THREAD

**Issue by TehPsychedelic** [The-4n/4NXCI#31]
Does it make sense for the temporary folder to be set on same path as output folder?
E.g User knows output folder has enough space, but currently the tool just uses CLI location as temp folder.

**Comment by The-4n** [comment]
Well if you want to work on GUI, do what ever you want,then make a PR
I'll review it and if there are ok, I'll merge it and give you the credits for sure

**Comment by The-4n** [comment]
Edited previous comment @TehPsychedelic 
My English is not that good so i apologies

**Comment by TehPsychedelic** [comment]
It's ok @The-4n. I'll send some PRs like #30 then. I just didn't want to be like rude and just send them out of nowhere, but I getcha it can also get tedious to open an issue for every thought :)

I will send a PR for temporary folder later so you can take a look.

**Comment by TehPsychedelic** [comment]
#35
