### ISSUE TITLE
Setting temporary folder (-t) deletes all *.nsp, *.xml and *.nca in folder

### ISSUE THREAD

**Issue by TehPsychedelic** [The-4n/4NXCI#34]
https://github.com/The-4n/4NXCI/blob/8cf4907cd70f894187e12160172e54c0bbdb9d2d/filepath.c#L125

When you set the temporary folder manually, it will delete all *.nsp, *.xml and *.nca at start of conversion. Which is dangerous if you set the temporary folder to where you have other NSPs already.

On top of that, if you set [temporary folder = output folder], at the end it will delete the converted NSP, so no conversion will take place essentially.

What I don't understand is why this happens, it should actually delete the whole directory according to that C code (this would be even worse as it would delete the original XCI too), but incidentally only XML, NCA and NSP.

**Comment by The-4n** [comment]
It works the way it should
Contents of temp gets deleted before and after conversion
Output and temp dirs must never be the same

The reason xci file is not get deleted is because it's already open in 4nxci so it can't get deleted

**Comment by TehPsychedelic** [comment]
Yeah I thought so of the XCI, the handle still opened, but still it's weird because if you have say "dummy.txt", "dummy.mp4", "dummy.docx" it won't delete those. When it "should" according to that generic deletion code.

But in any case do you think it would be appropriate to maybe include that in the documentation, that the temporary folder will be deleted? An user may use a folder to store all his converted NSPs and if he ever sets that to temporary too because of space/drive issues, then it would delete them.

**Comment by The-4n** [comment]
Added
