### ISSUE TITLE
Unknown meta type! Are keys correct?

### ISSUE THREAD

**Issue by 1kozlovsas** [The-4n/4NXCI#38]
Getting this error with Pokemon and Okami HD when attempting to use the GUI to convert them. 

And yes, the keys are correct and not outdated. They were freshly dumped with Lockpick JUST before I began the conversion process.

If the keys have been verified to be correct is there anything else that could be causing this?

**Comment by The-4n** [comment]
Reasons:
Lack of required keys, Wrong Keys, Corrupted XCI

**Comment by 1kozlovsas** [comment]
Lack of required keys-The keys were verified to match, they were dumped using Lockpick and in accordance with tutorials on how to use this application.
Wrong Keys-The keys were verified to match, they were dumped using Lockpick and in accordance with tutorials on how to use this application.
Corrupted XCI-At first I figured this wouldn't be likely since I get this error with multiple XCI's but it's possible that the source of these XCI's corrupted them, I'll look elsewhere and see if this pops up again.

Thanks!
