### ISSUE TITLE
List of the games that fail

### ISSUE THREAD

**Issue by rdmrocha** [The-4n/4NXCI#4]
Instead of creating lots of threads about these, let's centralize which XCIs are failing and why to help the development:

game: Sonic Mania Plus
trimmed XCI MD5: c28f426aee483a99864bef8aacd76c66
padded XCI MD5: a569177eaa2af59db31ab9bb89caf011
error msg: 

> Saving 1175e068bb8b1ae8fba5885516c9a133.nca to 4nxci_extracted_xci/1175e068bb8b1ae8fba5885516c9a133.nca
> Unknown NCA content type

**Comment by serviqual** [comment]
game: Let's sing 20148 hits français
No error with 4NXCI (Alpha 5) but error when launching on Switch (sorry but my Switch is in French Language) : "Vous avez quitté le logiciel car une erreur est survenue"
Same error with the game Syberia 2 in Alpha 4 but has been solved with Alpha 5 for this game.

**Comment by The-4n** [comment]
this issue is solved in v0.9-beta.1
