### ISSUE TITLE
Fail to turn xci to nsp, stop at turning to nca

### ISSUE THREAD

**Issue by bagamonjai** [The-4n/4NXCI#40]
Fail to turn the xci to nsp recently.
It stops when turning it into nca, and the exe close automatically and it doesn't patch it with nsp.
I have tried for 3 xci which is downloaded recently which come with the same problem. including,
The Caligula Effect Overdose (USA) [Softcobra.com].xci
Wizards Symphony (JP) [Softcobra.com].xci
Yunohana spring mellow times (JP) [Softcobra.com].xci

However, some xci that download one month before can still work properly and turn to nsp successfully.

Is it some update that need to be made?

**Comment by The-4n** [comment]
It seems you are missing new keys
Send me full 4nxci log

**Comment by bagamonjai** [comment]
https://www.youtube.com/watch?v=n3_9_1I3Occ&feature=youtu.be

**Comment by The-4n** [comment]
It says the video is unavailable
Send me your 4nxci log please
You can use GUI, it's easier
Also make sure to use the latest version

**Comment by dothackjhe** [comment]
What are the new keys needed if one is upgrading from version 2 of the app to the latest version (v4)?

**Comment by dothackjhe** [comment]
I think I have found out the problem: it might be the old "keys.dat."

Apparently, beginning in firmware 6.20, how the keys are dumped differs significantly from lower versions in that games that were dumped in XCI that requires at least firmware 6.20 cannot be converted to NSP using the old keys.

There's now a new method of dumping keys with firmware 6.20 or 7.0.1: it requires a Switch homebrew named "LockPick."

**Comment by bagamonjai** [comment]
> I think I have found out the problem: it might be the old "keys.dat."
> 
> Apparently, beginning in firmware 6.20, how the keys are dumped differs significantly from lower versions in that games that were dumped in XCI that requires at least firmware 6.20 cannot be converted to NSP using the old keys.
> 
> There's now a new method of dumping keys with firmware 6.20 up to 7.0.1: a Switch homebrew named "LockPick."

So exactly what can I do to turn it into NSp?

**Comment by dothackjhe** [comment]
You need to re-dump your keys.dat using the LockPick homebrew. 

https://github.com/shchmue/Lockpick

**Comment by dothackjhe** [comment]
Update:

Replacing the old "keys.dat" with one which comes as a derivative of the "LockPick" process to be used with the version 4.0 of NCXI does make it work.

**Comment by bagamonjai** [comment]
> Update:
> 
> Replacing the old "keys.dat" with one which comes as a derivative of the "LockPick" process to be used with the version 4.0 of NCXI does make it work.

Would you mind to provide the keys.dat of the new version? Because it's a bit complicated to follow the LOCKPICK process.
Thank you very much

**Comment by The-4n** [comment]
@bagamonjai Sharing keys is illegal
