### ISSUE TITLE
Filepath length problem since commit fcf6f5705c997096b42a95dd7d30529523845589

### ISSUE THREAD

**Issue by dezem** [The-4n/4NXCI#41]
Since commit fcf6f5705c997096b42a95dd7d30529523845589
Changes for the filepath.c from strncpy to memcpy

There is a failure with the filepath length for the params.
Only short paths are working.
Same bug exists on the reNXpack tool.

**Comment by The-4n** [comment]
Can you give me an example?

**Comment by dezem** [comment]
As example: 
4nxci path is "D:\Switch\Tools\4nxci\4nxci .exe"

If i run it for Captain Toad Treasure Tracker
not working:
4nxci.exe -k "prod.keys" "D:\Switch\Gamedumps XCI\Captain Toad Treasure Tracker.xci"

working (if i remove Tracker from the name):
4nxci.exe -k "prod.keys" "D:\Switch\Gamedumps XCI\Captain Toad Treasurer.xci"

**Comment by The-4n** [comment]
Check latest version and tell me the results

**Comment by dezem** [comment]
Last version 4.03 is working, thanks :+1:
