### ISSUE TITLE
Cannot be installed using devmenu

### ISSUE THREAD

**Issue by kot2002** [The-4n/4NXCI#5]
Converted NSPs cannot be installed using devmenu.

And installed apps does not run on open-source CFWs. (sig-patched atmosphere, ReiNX, etc.)

But if you install update NSPs for them, it runs normally.

It seems that games which have no updates only run on SX OS currently.

**Comment by chronoss09** [comment]
Something for me too, the game can't launch...

**Comment by The-4n** [comment]
the issue is resolved in v0.9-alpha.3
