### ISSUE TITLE
Corrupt NSP witch ROMMENU

### ISSUE THREAD

**Issue by chronoss09** [The-4n/4NXCI#7]
With the last build, i have a corrupt nsp file on ROMMENU, no icon is showing on rommenu but with Tinfoil and Devmenu, it work well and i can launch the without problem...

Game tested : Cave Story Plus and Captain Toad Treasure Tracker !

**Comment by chronoss09** [comment]
Sorry to inform you that NSP file work only on SX OS, it give me an error with ReiNX :-1:  but if you install the game with the update, it work on ReiNX :+1:

**Comment by The-4n** [comment]
the issue is resolved in v0.9-alpha.4

**Comment by chronoss09** [comment]
It work now, i have the icon on ROMMENU but can't play the game : error
