### ISSUE TITLE
run nsp files

### ISSUE THREAD

**Issue by rmorteza21** [The-4n/4NXCI#9]
hi
thanks for your work
i can convert xci games to nsp
and i can istall with dev menu
i use many cfw but cant run converted nsp files
my friend test files in sxos works
you can help me for run this games in cfw?
thank you

**Comment by The-4n** [comment]
use published sig patches as a workaround

**Comment by chronoss09** [comment]
Not work on other CFW, work only with SX OS !

**Comment by rmorteza21** [comment]
My friend test and answers with renix cfw and costum payload game works

**Comment by chronoss09** [comment]
I have the last build and nothing work, can u give me the link for his file please ?

**Comment by rmorteza21** [comment]
Send me your email

**Comment by chronoss09** [comment]
chronoss0109@gmail.com

**Comment by rmorteza21** [comment]
Enjoy :D

**Comment by chronoss09** [comment]
Ok, let me try this, this night !

**Comment by chronoss09** [comment]
It work bro, thanks alot :+1:

**Comment by rmorteza21** [comment]
My friend is number one in world

**Comment by chronoss09** [comment]
Not in this world :)
